### ISSUE TITLE
Language=>language is not maintained when user navigates back from Contact, Registration & discount details view

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#1000]
-Login to event app
-Go to contact on the left panel
-click on any contact to go to contact detail view
-change the language from right top
-Click back "<contacts "
-The all contacts page resets to english
Same issue persists with REgistration, & discount code on the left panel

**Comment by rishi9684** [comment]
Added in discount code 
As per discussed with sukant and lokesh we will add only for discount page
 for other page i.e contact and Reg we will keep same
