### ISSUE TITLE
Rec Session=>Related issues

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#1022]
#1 Rec session cannot be created if any kind of alert  eg validation alert is displayed, this happens only when group is selected ,with personal option ,it works fine
 https://www.loom.com/share/541eea8e22d74daa8af3a2017b232120
#2 Reset the form  when "+New Rec Session" is clicked else the slot duration is same as selected for previously created session and the Alert message is also displayed from previous session
#3 Dependent from #1016  =>Form cannot be saved after "No" is clicked after the Session overlap alert
 https://www.loom.com/share/081b3bf1eb2a44319413a2c492925716

**Comment by pallaviumap** [comment]
4)Dependent for #1015 ,after edit eg for group allowance, the form is not saved
https://www.loom.com/share/c14a7b6d897d4c41a5e7943c016254dd

**Comment by pallaviumap** [comment]
5)The form is not Reset for Day selection, same as it is not for days in date range

**Comment by pallaviumap** [comment]
6)No Rec session of any type can be created if the group allowance is changed

**Comment by pallaviumap** [comment]
7)Validate the Slot duration with the start n end time, else slot is not displayed on registration site
https://www.loom.com/share/b0497f61f4f1496fbacea75f7d60b343

**Comment by pallaviumap** [comment]
#1=>Accepted
#2=>Accepted
#3=>Reopened https://www.loom.com/share/11384072e13c480ebc93c8f93c10bc41
#4=>Accepted

**Comment by pallaviumap** [comment]
8)If for the previous session created custom time was selected, then for next new session created a part of custom time is displayed , and if without changing the duration of the slot if session is created then slots are created according to the custom time duration of the slot mentioned.
https://www.loom.com/share/da896aae94144d199a1ab059122f2e48

**Comment by pallaviumap** [comment]
9) provide mandatory validation if none of the days are selected from the checboxes

**Comment by pallaviumap** [comment]
In Test=> 
      #1=>Accepted
      #2=>Accepted
      #3=>Accepted
      #4=>Accepted
      #5=>Reopened -Not fixed
      #6=>Accepted
      #7=>Accepted
      #8=>Accepted

**Comment by pallaviumap** [comment]
10-Provide Validation for number of days for rolling days so as not to accept negative values else session is not created
https://www.loom.com/share/8163fceef4484e979a44b2672d14094d

**Comment by pallaviumap** [comment]
11-Provide validation for start date should be less than end date or end date should be more than start date while "Date range" option is selected while creating event or from event details.
**watch the video carefully-extra session for date not selected is created"
https://www.loom.com/share/c0f102284d3045988fc71361916dc997

**Comment by lokeshbitpod** [comment]
@pallaviumap pls verify 5, 9, 10

**Comment by pallaviumap** [comment]
12-
-From  calendar format ,click on "Add Availability" and check boxes for either all days of week or for selected ones & select for "Apply for Repeating Week days" & complete the form
-No availability is added which is ok coz the days or date for the session have ended
-Display an alert in such situation implying that the availability could not be added coz the session has edited ,so edit the session for extended availability and then add availability

**Comment by pallaviumap** [comment]
> @pallaviumap pls verify 5, 9, 10

=>5,9,10 Accepted

**Comment by pallaviumap** [comment]
12-Provide numeric and mandatory validation for rolling days field
https://www.loom.com/share/cc1d8beaae4342ae8d90c277ead1978e

**Comment by pallaviumap** [comment]
> #11 Provide validation for start date should be less than end date or end date should be more than start date while "Date range" option is selected while creating rec session from event details.

Validate the complete date and not just the day..session for the following is created
![image](https://user-images.githubusercontent.com/83949077/128995024-7857e400-361c-460a-9824-180bdd9d733a.png)

**Comment by pallaviumap** [comment]
#12-Accepted

**Comment by pallaviumap** [comment]
#11 -Accepted
Summary=>
#1-Accepted
#2-Accepted
#3-Accepted
#4-Accepted
#5-Accepted
#6-Accepted
#7 -Accepted
#8-Accepted
#9-Accepted
#10-Accepted
#11-Accepted
#12-Accepted
since all sub issues are resolved and accepted, So closing the Issue in whole
