### ISSUE TITLE
For jpy currency we are rounding of the ticket decimal values but in event detail view and in reg email still getting same decimal values

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#590]
**Describe the bug**
For JPY currency we are rounding off the ticket decimal values but in event detail view and in reg email still getting the same decimal values

**To Reproduce**
1. Create an event with JPY currency
2. Add new ticket in it with decimal values
3. Register for the event 
4. Check the registration email and reg detail view 

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/117773323-c9a61080-b255-11eb-96bd-43d378cf04a1.png)
![image](https://user-images.githubusercontent.com/69501912/117773409-e6424880-b255-11eb-85f1-a444aa6469ef.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome

**Comment by SukantGujar** [comment]
Tag this with the label bug and the release label for which this was found.

**Comment by mayurideshmukh7** [comment]
Done

**Comment by Bhagyshree10** [comment]
verified
