### ISSUE TITLE
Upload logo or upload picture form is not getting on google analytics 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#603]
**Describe the bug**
Upload logo or upload picture form is not getting on google analytics 

**To Reproduce**
1. Upload the org logo from administration and check the record in google analytics
2. Upload the speaker/Contact/Registration contact and check

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Comment by pallaviumap** [comment]
1)Upload for speaker image not shown in google analytics
2)For logo upload in administration ,its displaying the "Upload " action in console ,but yet not in analytics, will verify for logo upload after its displayed in analytics
