### ISSUE TITLE
Not able to select the seat map from Existing Seatmap Layout form 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#605]
**Describe the bug**
Not able to select the seat map from the Existing Seatmap Layout form 

**To Reproduce**
1.Go to normal venue type event 
2.Turn on the seatmap toggle 
3.click on select existing seatmap 
4.select the seatmap and check

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Comment by pallaviumap** [comment]
plz refer to #598 ,this is already reported
