### ISSUE TITLE
While creating recurring event, getting ticket price as 0 in recurring session section though it is paid

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#608]
**Describe the bug**
While creating a recurring event, getting ticket price as 0 in recurring session section though the ticket is paid

**To Reproduce**
1.Create a recurring event 
2.Add new ticket and make it as paid 
3.Go to the recurring session section
4.Check the ticket section

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome

**Comment by pallaviumap** [comment]
plz refer #593,this is already reported

**Comment by mayurideshmukh7** [comment]
> plz refer #593, this is already reported

Both are the different issues
