### ISSUE TITLE
Edit Organization details->no numeric validation for Phone number

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#615]
-Login to event app
-Go to administrations=>click on "edit" in Organization information
-No numeric validation for phone number 
![image](https://user-images.githubusercontent.com/83949077/118113423-e84a0a00-b403-11eb-9956-ee0395cfe3cb.png)

**Comment by pallaviumap** [comment]
Still No numeric validation
![image](https://user-images.githubusercontent.com/83949077/120141860-ee5d2a80-c1fa-11eb-9d77-7ca6b048834e.png)
![image](https://user-images.githubusercontent.com/83949077/120141931-092f9f00-c1fb-11eb-881a-f2a65d6571d0.png)

**Comment by lokeshbitpod** [comment]
No, I will update it and make allow more than 10.

**Comment by lokeshbitpod** [comment]
@SukantGujar 
What should be the max length for the phone field

**Comment by pallaviumap** [comment]
> No, I will update it and make allow more than 10.

Can be less than 10 as well!

**Comment by SukantGujar** [comment]
> @SukantGujar 
> What should be the max length for the phone field

I would suggest 15, per this

https://en.m.wikipedia.org/wiki/Telephone_numbering_plan
