### ISSUE TITLE
Check the spacing between the registration email template

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#616]
**Describe the bug**
Check the spacing between the registration email template

**To Reproduce**
1. Register for the different events and check the spacing 
2. Should be consistent for all templates

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/118138401-e42de480-b423-11eb-8b35-e9ef21f77913.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Comment by mayurideshmukh7** [comment]
Not Fixed for recurring event

**Comment by rishi9684** [comment]
please check for Reccuring event

**Comment by Bhagyshree10** [comment]
verified
