### ISSUE TITLE
Administration-->unable to edit the event registration url, even if it is not duplicate

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#623]
-Login to event app
-go to administration
-go to organization settings
-click on "Edit"
-change the event registration url such that it is not duplicate to already created urls for organizations
-click save--Keeps on loading
plz check the console Screen shot
![image](https://user-images.githubusercontent.com/83949077/118263230-a092b380-b4d3-11eb-9cb2-ccddc7350841.png)
![image](https://user-images.githubusercontent.com/83949077/118263277-adafa280-b4d3-11eb-8d99-71046222d8ad.png)

**Comment by lokeshbitpod** [comment]
Fixed #632

**Comment by pallaviumap** [comment]
Primary issue marked resolved with new dependent issues
