### ISSUE TITLE
Event>>Search Event is working for selected page only 

### ISSUE THREAD

**Issue by Bhagyshree1994** [bitpodio/bitpodjs#626]
**Describe the bug**
not able to search event on another page 

**To Reproduce**
1. Go to event app
2. create new event
3. go to live and draft events
4. click on next page 
5. search new backend name in search box

**Expected behavior**
when we search event it should search from all events 

**Screenshots**
![event1](https://user-images.githubusercontent.com/71262809/118293285-1fe5ae80-b4f7-11eb-92bf-0a93a97a6e67.PNG)
![event2](https://user-images.githubusercontent.com/71262809/118293301-2411cc00-b4f7-11eb-9d2c-a99170321d44.PNG)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser  chrome

**Comment by lokeshbitpod** [comment]
Fixed #632
