### ISSUE TITLE
Remove the star mark from new and edit timezone form heading 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#629]
**Describe the bug**
Remove the star mark from new and edit timezone form heading from lookups

**To Reproduce**
1. Go to Lookups 
2. Create a new/edit timezone 
3. Check form heading

**Desktop (please complete the following information):**
 - OS:Windows10
 - Browser : Chrome

**Comment by Bhagyshree10** [comment]
verified

**Comment by Bhagyshree10** [comment]
verified in prod
