### ISSUE TITLE
After login with google, when I click on the event tab it redirects to eventboard

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#630]
**Describe the bug**
After login with google, when I click on the event tab it redirects to eventboard

**To Reproduce**
1. Log in to event app on /dev with google
2. try to go to the events tab and check 

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Comment by Amartyakumar** [comment]
On any api or gql failure we should redirect the user back to the home route as per discussion with Sukant.Closing this

**Comment by Bhagyshree10** [comment]
verified
