### ISSUE TITLE
Check the avatar alignment on member detail view 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#631]
**Describe the bug**
Check the Avatar alignment from member detail view 

**To Reproduce**
1. Go to the Member detail view and check the avatar

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/118497397-a80bc400-b742-11eb-9071-104e2b33484c.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Comment by Bhagyshree10** [comment]
verified

**Comment by Bhagyshree10** [comment]
verified in prod
