### ISSUE TITLE
Venue Name is not displayed in the the event address on the registration site and email

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#635]
-Login to the event app
-create an event with Venue and add the "Venue Name" and all other details->save->create the event
-GO to the registration site and check the complete address-->"Venue name " not displayed
highlighted "Kidscommom " is the venue name which is not visible on the registration site
![image](https://user-images.githubusercontent.com/83949077/118635529-553d1580-b7f1-11eb-95ef-15e30d07f956.png)
![image](https://user-images.githubusercontent.com/83949077/118635837-ac42ea80-b7f1-11eb-89d2-a25c5a957e03.png)

**Comment by pallaviumap** [comment]
The Venue name is still not displayed if the Field is Edited and default value is changed
![image](https://user-images.githubusercontent.com/83949077/119631225-4f68b500-be2d-11eb-84e7-44d8bba7f147.png)
![image](https://user-images.githubusercontent.com/83949077/119631306-63acb200-be2d-11eb-92cf-9b58b8f76a25.png)

**Comment by rishi9684** [comment]
For Rec Event venue address changes need to do in API please check

**Comment by lokeshbitpod** [comment]
> For Rec Event venue address changes need to do in API please check

There is no change in the api as in mail we display only addess not name of the bussiness unit

**Comment by pallaviumap** [comment]
Venue name not displayed on event details page
![image](https://user-images.githubusercontent.com/83949077/123035461-fcbcf180-d408-11eb-93a6-aec32bd2f1cb.png)
![image](https://user-images.githubusercontent.com/83949077/123035548-2413be80-d409-11eb-8eee-c8b7064bb64c.png)
