### ISSUE TITLE
Feeds>>Title field is mandatory still able to create feed without any title

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#640]
**Describe the bug**
title field is showing mandatory for feeds but actully its not mandatory we can create feed without any title

**To Reproduce**
1. Go to community app
2. Click on feeds menu
3. create feed without any title 

**Expected behavior**
title should be mandatory

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/118811106-3c546300-b8ca-11eb-9c08-fd1a57134e92.png)

**Desktop (please complete the following information):**
 - OS: window
 - Browser :chrome

**Comment by Bhagyshree1994** [comment]
title field is still not mandatory on edit feed form 
![image](https://user-images.githubusercontent.com/71262809/118982073-af2c0f80-b998-11eb-94cf-a3d26ea5a89e.png)

**Comment by Bhagyshree10** [comment]
still edit form title is not mandatory

**Comment by rishi9684** [comment]
please check now

**Comment by Bhagyshree10** [comment]
verified
