### ISSUE TITLE
From the lounge page when I try to click on speakers Facebook, Linkedin or Twitter account link it redirects to 404 page 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#642]
**Describe the bug**
From the lounge page when I try to click on speakers Facebook, Linkedin, or Twitter account it redirects to 404 page 

**To Reproduce**
1. Create a speaker in event 
2. Add all the details 
3. register for the event
4. check lounge page
5. check the facebook, twitter and linkedin links 

**Desktop (please complete the following information):**
 - OS : windows10
 - Browser : Chrome

**Comment by Bhagyshree10** [comment]
verified
