### ISSUE TITLE
While creating new member type field is marked as mandatory but actually not 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#650]
**Describe the bug**
While creating new member type field is marked as mandatory but actually not 

**To Reproduce**
1. Go to the Community app
2. Create a new member 
3. Check type field 

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser :  Chrome

**Comment by pallaviumap** [comment]
change the validation message to appropriate one
![image](https://user-images.githubusercontent.com/83949077/124423205-4f3fcb80-dd82-11eb-9cd1-6b4f69651045.png)
