### ISSUE TITLE
While creating new member, if the user doesn't add the address then getting quama and blank spaces in member detail view 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#652]
**Describe the bug**
While creating a new member, if the user doesn't add the address then getting quama and blank spaces in the member detail view 

**To Reproduce**
1. Create new Member without adding address
2. Go to member detail view nad check the address fields

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/118993583-41d1ac00-b9a3-11eb-91c4-8179a6be0f8e.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Comment by mayurideshmukh7** [comment]
The location should also display a single dash like Member type when there is no address, getting blanc space now

**Comment by Amartyakumar** [comment]
Closing this as on adding the dash in the City or Country will make the inadequate.As it can happen that the user may add country and no City so it that case useless '-' will be added.So just adding a space instead of '-' as it will not break the ui look and feel.

**Comment by Bhagyshree10** [comment]
Verified
