### ISSUE TITLE
Check the add existing contact form UI from member detail view 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#653]
**Describe the bug**
Check the add existing contact form UI from the member detail view 

**To Reproduce**
1. Go to the Member detail view 
2. add existing contact from the contact grid
3. Check UI 

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/118994331-dd631c80-b9a3-11eb-9dbb-38ba430c0bb8.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : chrome

**Comment by mayurideshmukh7** [comment]
No need of scroll on form, as contents are not that long

**Comment by Amartyakumar** [comment]
Fixed again

**Comment by Bhagyshree10** [comment]
verified

**Comment by Bhagyshree10** [comment]
verified in prod
