### ISSUE TITLE
Create Single Event action is showing as Drawer.SingleEventAction

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#689]
**Describe the bug**
Create Single Event action is showing as Drawer.SingleEventAction

**To Reproduce**
1. Go to Event app 
2. Check Create Event action

**Screeenshot**
![image](https://user-images.githubusercontent.com/69501912/119509626-6d330d00-bd8e-11eb-8506-137d42ed5f91.png)

**Comment by Amartyakumar** [comment]
Fixed by @yash-bitpod

**Comment by Bhagyshree10** [comment]
verified
