### ISSUE TITLE
When I register for recurring event then not getting tickets in ticket sections where as getting placeholder as "TicketList"

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#695]
**Describe the bug**
When I register for recurring event then not getting tickets in ticket sections whereas getting placeholder as "TicketList"

**To Reproduce**
1.Register for recurring event 
2.Check email

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/119513426-d49e8c00-bd91-11eb-8c1a-da22727c8a98.png)

**Comment by mayurideshmukh7** [comment]
Getting two ticket icons
![image](https://user-images.githubusercontent.com/69501912/119670164-4b04c200-be56-11eb-8ddd-ec4d9ee2ff20.png)

**Comment by Bhagyshree10** [comment]
Verified
