### ISSUE TITLE
Ticket Template:- Change the alert message while un-assigning the ticket template

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#701]
-Log in to event app
-go an existing event with tickets or create a new event with tickets
-Go to event details page
-scroll down to ticket grid =>click on 3 dots to go to assign template
-Assign a template and navigate back to ticket grid
-Go to Assign template again and Un assign the template
-change the alert from delete to "Unassign" ,User feeels as if he is deleting the template while he is only un assigning
![image](https://user-images.githubusercontent.com/83949077/119632982-ebdf8700-be2e-11eb-907c-31c3d4c12993.png)

**Comment by yash-bitpod** [comment]
@pallaviumap The user is deleting the template specific to the event. E.g.: 
1. A user selected the template
2. Modified it in some way
3. unchecked the checkbox

The modifications specific to the template for the event will be deleted.

**Comment by yash-bitpod** [comment]
Resolved with #720
