### ISSUE TITLE
Ticket Template:- the same form is displayed with alerts if it is closed and opened again unless refreshed

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#705]
-Go to administration ->ticket template ->New template
-add the name, size & RTE=>delete all the details ->alert is displayed->close the form->again open it by clicking on the "New template"->the form is not reset, it still displays the form fields with alert
https://www.loom.com/share/c62d1edf3d4d47bea590fcae9d103d9a

**Comment by yash-bitpod** [comment]
Resolved with #720

**Comment by pallaviumap** [comment]
RTE alert is still displayed
![image](https://user-images.githubusercontent.com/83949077/120143996-cbcd1080-c1fe-11eb-9618-f6e8582dbbae.png)

**Comment by Amartyakumar** [comment]
Tried to reproduce it but its working on my side.
https://www.loom.com/share/3fdd40d9367c4dd5a468bbffd05028d7

**Comment by pallaviumap** [comment]
its regenerating on my side
https://www.loom.com/share/e8aa81a3421d4abcace9dbbfdc7f3307
