### ISSUE TITLE
After refresh not getting data in event name drop down on check in page

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#710]
**Describe the bug**
After refresh not getting data in event name drop down

**To Reproduce**
1. Go to the event detail view
2. Go to check-in page from three dots
3. Check the check in page
4. Refresh the page and check

**Comment by rishi9684** [comment]
As discussed with lokesh need to check in lookup component

**Comment by Bhagyshree10** [comment]
Verified

**Comment by Bhagyshree10** [comment]
verified in prod
