### ISSUE TITLE
Discountcode>>when we select discount code and open actions are not showing proper

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#712]
**Describe the bug**
when we select discount code and open actions then scroll is showing in actions

**To Reproduce**
1. Go to event app
2. click on discount code
3. select discount code
4. click on 3 dot action
5. sroll is showing in action

**Expected behavior**
scrolling should not display 

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/119677361-48a56680-be5c-11eb-8727-f597e1399ede.png)

**Comment by pallaviumap** [comment]
No scroll is displayed in the action menu
![image](https://user-images.githubusercontent.com/83949077/128688989-3f98794e-cd6d-40f6-afe1-b31617c831f9.png)
