### ISSUE TITLE
While sending an email invite from community app, it remains in executing state, not getting email

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#718]
**Describe the bug**
While sending an email invite from the community app, it remains in executing state, not getting an email

**To Reproduce**
1. Go to Community app 
2. From contact tab send an email invite 
3. check the email

**Comment by Amartyakumar** [comment]
@SukantGujar For this we will need to check the backend changes for not getting the emails.Will have to debug this.Not having any clue for now.

**Comment by SukantGujar** [comment]
@lokeshbitpod please take a look

**Comment by Bhagyshree10** [comment]
Verified
