### ISSUE TITLE
NoTicketEvent>>for no ticket events actions menus are showing for tickets grid

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#721]
**Describe the bug**
when we create noticket event on event detail view getting action menu for tickets grid

**To Reproduce**
1. Go to event app
2. Create no ticket Event 
3. check action for ticket

**Expected behavior**
Actions should not display for no event

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/119820235-e0638d00-bf0e-11eb-97fa-63cb7da62e0a.png)

**Comment by yash-bitpod** [comment]
Resolved with #723

**Comment by Bhagyshree10** [comment]
verified
