### ISSUE TITLE
Black Theme issues

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#722]
**Describe the bug**

Black Theme Issues

1.Bitpod logo should display in its colors and name in white in black theme all over the app
2.RTE drop down getting white background
3.Eventboard top tiles skeleton is still white
4.Not able to read the event name from the event timeline
5.Check create event form, back button is still white 
6.In create event form address field text is in black color 
7.Not able to see the text on badge templates from the administration
8.Getting gray line at top and patches at bottom on seat map app 
9.Not getting some images from integration app in black theme

Steps to Reproduce
1.Change the event app theme as black and check

**Comment by pallaviumap** [comment]
Reopened for:-
1)Bitpod logo should display in its colors and name in white in black theme all over the app ,the name is displayed in black/dark grey 
2)Address Drop down while creating event is in white
3)All images in the  integration app are not displayed same

**Comment by pallaviumap** [comment]
=>Bitpod logo will not be displayed in color as in normal theme (As suggested by rishi)
=>Rest Accepted so closing the issue
