### ISSUE TITLE
The snackbar message size for recurring event is very small as compared to other events, should be same for all 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#726]
**Describe the bug**
Check the snack bar message size for recurring event, it's very small as compared to other events, should be the same for all 

**To Reproduce**
1. Go to Recurring event
2. Check the snack bar for all actions

Screenshot
![image](https://user-images.githubusercontent.com/69501912/120141882-f5843880-c1fa-11eb-918b-c35eef7d8278.png)

**Comment by neeraj-gulati** [comment]
@mayurideshmukh7 
#1 screen shot missing 
#2 issue title should not start with check

**Comment by neeraj-gulati** [comment]
a lot of time dev asks for calls with you because screenshot and looms are missing.
