### ISSUE TITLE
Event Status:- Event status is is not marked "Registration Closed" even after the Event is closed.

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#738]
-Login to event app
-Go to a closed Event
-Verify the event status
![image](https://user-images.githubusercontent.com/83949077/120140031-4c880e80-c1f7-11eb-8d90-3834b43d6728.png)

**Comment by Amartyakumar** [comment]
@SukantGujar This is regarding 1 test case where we have created an event with some end date.But once we cross the end date we should close the event.So i will have to check as currently the stepper value is based upon the Status field which we manually make changes.So how can we automate this process?

**Comment by SukantGujar** [comment]
One way would be to perform this check when the event is being requested, in the UI.

**Comment by SukantGujar** [comment]
I would have recommended beforeRead but that has performance implications when a lot of events are being read.

**Comment by Amartyakumar** [comment]
Okay then I think when we are loading the UI of the event then I should check if the event end date is less than the current date or not.If less then will have make a patch request to event model with Status field as Closed and then get the data back.Will it be like this.So the stepper values will also be updated
