### ISSUE TITLE
App drawer - open every app in new tab 

### ISSUE THREAD

**Issue by neeraj-gulati** [bitpodio/bitpodjs#739]
#1 When i go to admin then i loose view of event app. it is better we open apps in new tab and keep current tab intact.
#2 First word of browser title should be app name then bitpod. "Event Bitpod", "Administration Bitpod", "Seat Map Bitpod" etc..

**Comment by pallaviumap** [comment]
combined #1315 from issue List=>add Hyper link to bitpod Logo on the Left that redirects to EventBoard

**Comment by pallaviumap** [comment]
The title for e-signature is not "E-Signature Bitpod"
![image](https://user-images.githubusercontent.com/83949077/120188379-aeff0000-c233-11eb-8b64-43b5134cc704.png)

**Comment by pallaviumap** [comment]
Survey Page does display title "Survey Bitpod"
![image](https://user-images.githubusercontent.com/83949077/120446759-813ac800-c3a7-11eb-9553-d0d5b3ff7215.png)

**Comment by pallaviumap** [comment]
the bitpod logo points to
https://disguiseevents-event.test.bitpod.io/apps/event/eventboard    and not
https://disguiseevents-event.test.bitpod.io/admin/apps/event/eventboard so redirects to a  blank page
![image](https://user-images.githubusercontent.com/83949077/120447199-fad2b600-c3a7-11eb-89a8-84648062625a.png)

**Comment by neeraj-gulati** [comment]
Survey title is fine, it is a different application, not part of event app.
