### ISSUE TITLE
Member's image upload section should be like contacts, not looking good now 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#742]
**Describe the bug**
Member image upload section should be like contacts, not looking good now 
   - Member image is too small
   - Check Member name alignment

**To Reproduce**
1. Go to Member detail view from Community app
2. Upload the image and check with the contact image

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/120161725-443ecc00-c215-11eb-8d3e-22add35b4350.png)

**Comment by Bhagyshree10** [comment]
verified
