### ISSUE TITLE
After refresh Contact's and Member's detail view skeleton gets break 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#743]
**Describe the bug**
After refresh Contact's and Member's detail view skeleton gets break 

**To Reproduce**
1. Go to the Member and Contact detail view 
2. Refresh the page 
3. and check skeleton

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/120162383-f1b1df80-c215-11eb-9f7c-08ddff3caa1e.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Comment by Bhagyshree10** [comment]
Verified

**Comment by Bhagyshree10** [comment]
verified inprod
