### ISSUE TITLE
Edit Member information and Edit Address information both forms are same

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#744]
**Describe the bug**
Edit Member information and Edit Address information both forms are the same

**To Reproduce**
1. Go to Member detail view from Community app
2. Check Edit Member Information and Address Information form
3. Check the form name as well

**Screenshots**
![image](https://user-images.githubusercontent.com/69501912/120162946-8d435000-c216-11eb-915f-3a663a5a3d4d.png)

**Comment by Amartyakumar** [comment]
@Bhagyshree10 this is similar to the one we have in CRM.Here both the address and member edit form are similar.So its showing similar form

**Comment by neeraj-gulati** [comment]
@Bhagyshree10 changing status to minor. We can live with the same form for now. Not critical for June 2021 release

**Comment by pallaviumap** [comment]
As discussed with sukant, the form will remain same ,but when address form edit is clicked ,then the same member form but with focus on address portion is opened
