### ISSUE TITLE
Add Existing sponsor from event details page glitches

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#751]
-Login to Event app
-Create a new event or go to existing one
-go to event Details page
-Scroll down to "Sponsor Grid"
-Click on "add from Existing Sponsor"
-The newly opened window glitches
https://www.loom.com/share/9c350a6b93034ca38cdd88d3f6480023

**Comment by pallaviumap** [comment]
plz check for other org than bitpod.
add more than 10 sponnsors.
https://disguiseevents-event.test.bitpod.io/admin/apps/event/event/60a391948d2be4000a069970

**Comment by SukantGujar** [comment]
@pallaviumap Can you elaborate what's the issue now?

**Comment by SukantGujar** [comment]
Please add screenshots and other evidence to understand the issue.

**Comment by pallaviumap** [comment]
> Please add screenshots and other evidence to understand the issue.
@SukantGujar 
1)Comment added yesterday includes the scenarios to be tried to reproduce the issue 
2) and the link for event and organization for which the issue still persists

**Comment by SukantGujar** [comment]
Ok, so the issue presents itself in it's entirety when more than 10 sponsors are added?

**Comment by rishi9684** [comment]
> Ok, so the issue presents itself in its entirety when more than 10 sponsors are added?

i think issue is with when i am login with google
