### ISSUE TITLE
After setup connection, status check box shows active but actually not 

### ISSUE THREAD

**Issue by mayurideshmukh7** [bitpodio/bitpodjs#753]
**Describe the bug**
After setup connection, status check box shows active but actually not 

**To Reproduce**
1. Go to Integration
2. Setup the connection and check

**Screenshot**
![image](https://user-images.githubusercontent.com/69501912/120199205-9fd27f00-c240-11eb-9c6b-7c06b2c3e8dd.png)

**Comment by Bhagyshree10** [comment]
Verified
