### ISSUE TITLE
Sponsor:- Sponsor cannot be added or edited from the event details page after duplicate email id alert is displayed and email id modified again

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#763]
-login to event app
-Create a new event or go to an existing one
-scroll down to Sponsors grid
-Add a new sponsor  with duplicate email id=>alert displays=>change the email id
-Still the sponsor cannot be created
-Same for edit
https://www.loom.com/share/bfc79c7389f94226abbd996020992ff4

**Comment by pallaviumap** [comment]
https://www.loom.com/share/807e5a177cc04939976ae2af1d4f574c

**Comment by rishi9684** [comment]
working on my side
please check
