### ISSUE TITLE
Rec Session:-No availability for 1st day is shown if "Date range option" is selected 

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#790]
-Login to event app
-Create a new Rec event with date range and more than 2 rec sessions
-Publish the event and register
-Session slot for 1 st day is not displayed
https://www.loom.com/share/9dcab2fbfe5d45ad872426b616c57b5f
https://disguiseevents-event.test.bitpod.io/admin/apps/event/event/recurring/60b9a748b0444f000af9c669
https://disguiseevents-event.test.bitpod.io/events/ticketvalidation1-tickets-60b9a748b0444f000af9c669/register/session

**Comment by pallaviumap** [comment]
-After rec event creation if we try to add new rec session from event details page ,then 1st session is created successfully, later if we try to create another session then its slots are not created and thus not displayed on registration site. The form is not reset with every "New Recurring Session" addition

**Comment by lokeshbitpod** [comment]
As discussed with @SukantGujar will need to rebuilt the form again 
Will move to next release

**Comment by pallaviumap** [comment]
As suggested by Lokesh, henceforth issues related to rec session will be added under 1 new issue #1022 .
Any dependent issues related to #1016,#1015 ,#790 #782 will be added to #1022
So closing the above 4 issues, for any further details on these issues plz reference #1022
