### ISSUE TITLE
Feed>>when there is no feeds we should display proper message

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#803]
**Describe the bug**
when no feeds we should display proper message like no feeds are available

**To Reproduce**
1. Go to event app
2. Click on community app
3. click onfeeds
4. See message

**Expected behavior**
when no feeds we should display proper message like no feeds are available

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/121036052-11c04080-c7cc-11eb-90a8-81a183437886.png)

**Comment by neeraj-gulati** [comment]
@rishi9684 Add messages for eSignature, Integration and Seat map as well pls

Feed >>> A place to share stories and update with your community!

Seat Map >>> With seat maps you can offer seat selection for your events. To create a new seat map click New Seat map or click existing seat map to edit.

Integration>>> There are always cases where you would like to integrate Bitpod with other systems, integrations helps you do that. Mouse over to setup the connection and start integrating.
