### ISSUE TITLE
eSignature>>request detail view ui is broken

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#808]
**Describe the bug**
request detail view ui is broken when we click on any request 

**To Reproduce**
1. Go to esign app
2. Click on any request
4. See UI

**Expected behavior**
all grids are not in proper allinement

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/121202104-aa20f880-c892-11eb-8aa4-aa36c974b3f5.png)

**Comment by pallaviumap** [comment]
Below is the current UI and as suggested by Rishi it is supposed to be as displayed
![image](https://user-images.githubusercontent.com/83949077/125422272-fc0c9097-2737-4837-817b-57939560fc3a.png)

**Comment by pallaviumap** [comment]
Same UI as in test
![image](https://user-images.githubusercontent.com/83949077/126766813-a0671b40-dacd-4e93-bd71-7214ff9b9604.png)
