### ISSUE TITLE
esignature>>when we click on list skeleton is getting changed for completed and decline request 

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#822]
**Describe the bug**
when we click on list skeleton is getting changed for completed and decline request 

**To Reproduce**
1. Go to esign 
2. Click on list 
3. select as completed 
4. See ui

**Expected behavior**
skeleton should be same for all list 

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/121532808-52fb5f00-ca1d-11eb-9704-6d9839a978bb.png)

**Comment by rishi9684** [comment]
its not skeleton issue.
the issue regarding tiles only tile was not corrected in other view like in above screenshot

**Comment by pallaviumap** [comment]
Skeleton is same as below for all types
![image](https://user-images.githubusercontent.com/83949077/125422942-c36f4ed8-7dae-4a11-a3f1-4dc97318c662.png)
