### ISSUE TITLE
Session & Ticket Selection conflict

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#831]
-Currently we are allotting tickets to a session for which the user is unaware as of which ticket is allotted to which session.
-So the user has to select the ticket which could be more than 1 and then find which ticket is allotted which session.
-instead the user should be able to first select a session and then tickets should be displayed accordingly.
-The end user will be more interested in the session and least bother about tickets.
-Eg:-
there is a kids event with different sessions and different tickets allotted to the sessions.
Sessions:-face painting, bouncing house , pool activity.
tickets:- different tickets for different sessions.
as a end user/parent we will like to see what sessions are there and then enroll for them ,even more than 1.

**Comment by neeraj-gulati** [comment]
@pallaviumap we will keep this on hold for now. There is a customer using this feature but they have not complained about it. Will wait for a custom to ask this.

**Comment by pallaviumap** [comment]
okay,got it

**Comment by pallaviumap** [comment]
As suggested by Neeraj -Not to be implemented until customer request
