### ISSUE TITLE
PayTM business integration 

### ISSUE THREAD

**Issue by neeraj-gulati** [bitpodio/bitpodjs#833]
Jagan had done PayTM payment gateway integration, it needs to be tested and issues to be fixed.

As far i know there was a reference to JS file reference in index.html, file URL has merchant id in it, so instead of hard coding the link reference we need to make part of it as dynamic. 

@SukantGujar can you check and add more comments to it?

**Comment by neeraj-gulati** [comment]
![image](https://user-images.githubusercontent.com/68544907/122011070-5a35ba80-cdd9-11eb-8a49-2ff08b8e3d75.png)
need to replace selected string from org specific value from paytm connection in connection model.

**Comment by SukantGujar** [comment]
@yash-bitpod https://www.npmjs.com/package/scriptjs

**Comment by pallaviumap** [comment]
Paytm business integrated.
