### ISSUE TITLE
USER PROFILE>>bottom side ui is moving

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#851]
**Describe the bug**
bottom side ui is moving ON Mouse actions

**To Reproduce**
1. Go to user profile
2. scroll down to bottom
3. see action on mouse

**Expected behavior**
UI Should NOT MOVE

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/122206290-d6ee9480-cebe-11eb-996c-e563b5d07436.png)

**Comment by pallaviumap** [comment]
No UI changes on mouse hover or movement
https://www.loom.com/share/40ef0abb4ad34ade9405d6eafc5c1cd6
