### ISSUE TITLE
Check in>>when i open registration from check in view and come back event dropdown is reset to default

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#852]
**Describe the bug**
when i open registration from check in view and come back event dropdown is reset to default

**To Reproduce**
1. Go to EVENT app
2. Click on event
3. go to check in page
4. select another event
5. open registratioN
6. click on back button
7. 

**Expected behavior**
selected event should displaY

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/122225170-76695280-ced2-11eb-85d7-1a0264432a5a.png)

![image](https://user-images.githubusercontent.com/71262809/122225251-85e89b80-ced2-11eb-922d-5072b1a19483.png)

![image](https://user-images.githubusercontent.com/71262809/122225341-9ac52f00-ced2-11eb-95a1-90c74d1a56d3.png)

**Comment by neeraj-gulati** [comment]
@pallaviumap when going back last selected event should be there in drop down
