### ISSUE TITLE
Paytm Registration=>attendee status not set and displayed

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#853]
-after registration from Paytm, attendeee status is not set and  displayed
![image](https://user-images.githubusercontent.com/83949077/122231553-242b3000-ced8-11eb-90e7-f7e37287bbfc.png)

**Comment by lokeshbitpod** [comment]
Pls verify all the payment gateways once

**Comment by pallaviumap** [comment]
Verified in test and so can proceed with changes in prod
