### ISSUE TITLE
admin site logo should also be based on domain  

### ISSUE THREAD

**Issue by neeraj-gulati** [bitpodio/bitpodjs#855]
take the main domain from url, do not consider subdomain. In case of event.bitpod.io - main domain is bitpod.io
in case of register.wbcsd.org main domain is wbcsd.org. 

user this domain to get logo image and then show that logo, if that domain logo is not found then show bitpod.io logo

**Comment by rishi9684** [comment]
deploy on /gs
https://lucky.workpay.io/gs/

**Comment by pallaviumap** [comment]
Tested for event app with bitpod .io as main domain and event as subdomain.
Images are displayed respective to the folder location in cloudinary.
Logo in sub domain take priority over the logo in main domain if images for logo are present in both the folders.
If no images for logo are in either of the folders of main n sub domain then default bitpod logo is displayed

**Comment by pallaviumap** [comment]
Tested by Neeraj on Prod
