### ISSUE TITLE
Members>>add existing contact is not working  

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#863]
**Describe the bug**
when we try to add existing contact its not getting added 

**To Reproduce**
1. Go to COMMUNITY APP
2. Click on members
3. aDD existing contacT

**Expected behavior**
should ABLE  TO ADD EXISTING CONTACTS

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/122417656-46d84a00-cfa7-11eb-815c-8dba2b873d8c.png)

**Comment by pallaviumap** [comment]
https://www.loom.com/share/b540bff5829443d8a3db120c537b41dc
The process does not get completed
