### ISSUE TITLE
UserProfile>>when we try change Password new password Validation is not working

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#870]
**Describe the bug**
when we try change Password new password Validation is not working

**To Reproduce**
1. Go to UserProfile
2. change Password

**Expected behavior**
when we try change Password new password Validation is should work

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/122563814-4650b980-d062-11eb-9518-4c9c728a2d1b.png)

**Comment by Bhagyshree10** [comment]
old password and new password should not be same 

![image](https://user-images.githubusercontent.com/71262809/123426012-7b1fbc00-d5e0-11eb-8c32-c9f393796e33.png)

**Comment by Amartyakumar** [comment]
We never match old password with the new and confirm password. As the new and confirm password is same the error is not thrown

**Comment by Bhagyshree10** [comment]
Verified
