### ISSUE TITLE
My Registrations =>provide a header and footer on My Registrations Page"

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#878]
-Provide heater and footer (as on registration site) on My Registrations Page
![image](https://user-images.githubusercontent.com/83949077/122884755-13593f00-d35c-11eb-8896-e87f06404225.png)
![image](https://user-images.githubusercontent.com/83949077/122884848-2bc95980-d35c-11eb-954d-28f0c8c12194.png)

**Comment by pallaviumap** [comment]
-Logo on the top right should be of the organization and not bitpod
-The color of the header is not as displayed on registration site
![image](https://user-images.githubusercontent.com/83949077/124412176-8bb3fd00-dd6b-11eb-995a-762637dc6352.png)

**Comment by rishi9684** [comment]
as discussed with neeraj for my registration page admin logo header will be same like admin site

**Comment by pallaviumap** [comment]
ok.will close the issue then.

**Comment by pallaviumap** [comment]
Accepted in prod
Tested the header n footer for other things on My Registration page like "registration not found" or error messages or correct registration displayed etc ; the header n footer is displayed correctly 
![image](https://user-images.githubusercontent.com/83949077/126481792-f73f1136-3bba-491a-a8f8-4429bd204e69.png)
