### ISSUE TITLE
Single Event=>City ,State, country displayed twice if venue address selected from drop down

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#882]
#1 >>
-Login to event app
-click "Create Event"=>single event
-Select venue=>address
-start typing and select any address from the drop down=>city, state, country fields gets auto populated=>complete the creation and go to event details page
-Check the address=>City ,State ,Country displayed twice 
-https://www.loom.com/share/c137b713b05a43448150b31a396cbf2e
![image](https://user-images.githubusercontent.com/83949077/123034005-5a9c0a00-d406-11eb-8593-4e3f0ff106f9.png)

**Comment by pallaviumap** [comment]
when Cities, states n countries with abbreviations are used in address form drop down ,then these are displayed twice 
![image](https://user-images.githubusercontent.com/83949077/126482550-14c53ea5-4334-49a6-b9c7-928ae48d4458.png)

**Comment by pallaviumap** [comment]
duplicity persists for  Registration email ,Registration site & Lounge
![image](https://user-images.githubusercontent.com/83949077/127478925-4b7b1497-b727-4fe8-bcd2-86253236a0c6.png)
![image](https://user-images.githubusercontent.com/83949077/127479078-e3cbdaa6-aa99-4a5a-8f6a-1b9a9d38cdd6.png)
![image](https://user-images.githubusercontent.com/83949077/127479235-954e11fb-a790-4bba-819f-f60a0a989a05.png)

**Comment by pallaviumap** [comment]
2>>Resolved & Accepted (For States n countries with abrrevations)
3>>Reopen (Registration Email)
4>>Reopen (Registration site)
5>>Reopen(Lounge)
![image](https://user-images.githubusercontent.com/83949077/127991567-1832c12a-7627-4c08-9a7f-7b7f8e7e990b.png)
![image](https://user-images.githubusercontent.com/83949077/127992320-0c2c061c-1465-4b1f-87ec-cddb91854e9c.png)
![image](https://user-images.githubusercontent.com/83949077/127992332-d8ee7e15-ab3d-4cdc-904e-dd15c85a0b02.png)

**Comment by Amartyakumar** [comment]
5 fixed

**Comment by pallaviumap** [comment]
> #5 fixed 
-Accepted for Single Event lounge
-Cannot be tested for Rec event lounge due to issue  #1066

**Comment by Amartyakumar** [comment]
#4
#5
Fixed

**Comment by pallaviumap** [comment]
> #4
> #5
> Fixed

#4-Accepted
#5-Will be verifies after #1066 is resolved

**Comment by Amartyakumar** [comment]
#3 fixed

**Comment by pallaviumap** [comment]
#5-Accepted(Rec events lounge does not display address but displays the type of Meeting, For single events the lounge displays the address correctly)
#3-Reopened-NotFixed
![image](https://user-images.githubusercontent.com/83949077/129139348-da6a1e2d-2128-4d5e-a268-620f07dabd74.png)

**Comment by pallaviumap** [comment]
#1 Accepted
#2 Accepted 
#3 Accepted 
#4 Accepted
#5 Accepted
