### ISSUE TITLE
Print Badge=>the print preview does not display correct UI

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#884]
the print badge preview comes out as in the screen shot where the code is partially hidden behind guest label
![image](https://user-images.githubusercontent.com/83949077/123042880-18c69000-d415-11eb-8bab-94e3b1938325.png)

**Comment by pallaviumap** [comment]
The issue is resolved in test but open in prod
https://www.loom.com/share/469ffc287e6d41fda81710ae058c74d7

**Comment by pallaviumap** [comment]
There is print issue with one of the badges..as discussed in the call

**Comment by rishi9684** [comment]
for that badge also resolved issue
