### ISSUE TITLE
Paytm=>in case UPI id is selected the pop up does not display the expire time

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#891]
-after UPI option is selected ,the pop up displays no expire time 
![image](https://user-images.githubusercontent.com/83949077/123210558-c9996180-d4df-11eb-9ed2-acd84be086c3.png)
![image](https://user-images.githubusercontent.com/83949077/123210587-d5852380-d4df-11eb-96bc-b9567ddcc14a.png)

**Comment by yash-bitpod** [comment]
A timer is already displayed... please scroll down.
![image](https://user-images.githubusercontent.com/74710904/123763469-752c2280-d8e1-11eb-8ae3-7d145076dc57.png)

**Comment by pallaviumap** [comment]
![image](https://user-images.githubusercontent.com/83949077/123767113-df929200-d8e4-11eb-8f99-dcc482281ee4.png)
nothing on my side and there is no scroll option as well

**Comment by pallaviumap** [comment]
![image](https://user-images.githubusercontent.com/83949077/123767113-df929200-d8e4-11eb-8f99-dcc482281ee4.png)
nothing on my side and there is no scroll option as well
