### ISSUE TITLE
Event>>search event option position is changed

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#893]
**Describe the bug**
search event option position is changed.

**To Reproduce**
1. Go to event app
2. Click on live and draft events
3. check search button

**Expected behavior**
search event option position should correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/123264023-3ed45900-d517-11eb-84ee-4e24f12e5ab8.png)

**Comment by Bhagyshree10** [comment]
verified

**Comment by pallaviumap** [comment]
this is the expected position after confirming with Rishi , So accepting in prod
![image](https://user-images.githubusercontent.com/83949077/126457837-76093d7a-38a2-4302-860d-83fc66f20efd.png)
