### ISSUE TITLE
Event Details Page=>display image inline with description in right panel if image is added in RTE while event creation

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#896]
-Login to event app
-Create an event with adding an image in RTE
-Go to the event details page of the created event=>display uploaded image inline with description in the right panel
![image](https://user-images.githubusercontent.com/83949077/123374227-69b8be80-d5a4-11eb-82cb-41d08e269dc6.png)

**Comment by rishi9684** [comment]
as discussed with amartya and like old site we need to show only text.
Also removed html tags and showing plain text

**Comment by pallaviumap** [comment]
As discussed with Sukant, the image should be displayed along with the description,(Same as it is displayed for Cancellation policy below)
![image](https://user-images.githubusercontent.com/83949077/128127018-70b294f3-fde4-46bc-a0e7-6a199ff84e07.png)
