### ISSUE TITLE
UserProfile>>when we have large address in user profile its not showing on detail view

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#900]
**Describe the bug**
all address on profile details is not showing if address field is large 

**To Reproduce**
1. Go to event app
2. Click on 'user profile 
3. Add larger address in add field 
4. save the changes'
5. check the address

**Expected behavior**
All address should display on detail view 

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/123430226-8de8bf80-d5e5-11eb-98a9-d390b54e8040.png)

**Comment by Bhagyshree10** [comment]
Verified in test

**Comment by pallaviumap** [comment]
Accepted in prod
![image](https://user-images.githubusercontent.com/83949077/126450124-5aa4a641-b174-42c4-aab0-bd4f10d39d60.png)
