### ISSUE TITLE
User Profile>>when we enable 2 factor and edit the profile detail on save 2 factor status is getting changed 

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#901]
**Describe the bug**
when we enable 2 factor and edit the profile detail on save 2 factor status is getting changed 

**To Reproduce**
1. Go to event app
2. Click on user profile 
3. Enable 2 factor 
4. edit profile details 
5. check 2 factor

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bhagyshree10** [comment]
Verified in test

**Comment by pallaviumap** [comment]
Accepted in prod
https://www.loom.com/share/08497a54ac8246e398738f67ef526cf4
