### ISSUE TITLE
Event details page=>Delete functionality for ticket not working in other orgs

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#902]
-Login to event app for any org other than Bitpod
-Go to the event details page of any existing event
-Scroll down to Ticket Grid
-Select any ticket=delete
-confirmation alert is displayed=>click yes
-Ticket is still not deleted
https://www.loom.com/share/a62fd587b9c64a7ea9fbd56a71ad1d6a
https://www.loom.com/share/c0639f52629a4d908543925f22a4f144

**Comment by lokeshbitpod** [comment]
I have tried for many events but not able to reproduce. Pls provide exact steps

**Comment by pallaviumap** [comment]
the regeneration of the issue is random currently.Will try to find out exact steps for reproduction of the issue. Until  then marking it as Resolved-Random.

**Comment by pallaviumap** [comment]
Accepted in prod
https://www.loom.com/share/a8b8237b37c646e5b6a483ff93450198
