### ISSUE TITLE
on lounge page >>when address is large ui is not showing properly 

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#907]
**Describe the bug**
on lounge page if  venue of event is large then its not showing properly

**To Reproduce**
1. Go to event app
2. Register venue type  event with large address
3. check lounge page

**Expected behavior**
lounge page venue should display properly 

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/123629927-82d69f00-d832-11eb-8aab-b8772b23ea56.png)

**Comment by Bhagyshree10** [comment]
Verified

**Comment by pallaviumap** [comment]
1)The address displays too many spaces between the words
![image](https://user-images.githubusercontent.com/83949077/126268815-f100f6f3-6ad6-4ca2-9d3b-4e18bd4067c6.png)
![image](https://user-images.githubusercontent.com/83949077/126268738-f2295da2-ff98-4a00-a406-259c8eaa3630.png)
