### ISSUE TITLE
Integration=>Edit functionality does not work for connections

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#912]
-Login to event app
-go to app drawer=>integration
-click on 3 dots of any already set up connection=>Edit=>change values=>click "Save"=>does not proceed
https://www.loom.com/share/1129e6af398d4edb8ba9c874ed3b4cbb

**Comment by lokeshbitpod** [comment]
Pls deploy the rls_03-06-2021 it is fixed on 30-06-2021 after sync from development branch
