### ISSUE TITLE
Paypal=>The UI after adding card for payment is not appropriate

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#913]
-Go to the registration site of an event with paid tickets and braintree/Paypal set as payment gateway
-Proceed to payemtn=>click on paypal button
-Add a card=>check the UI after the card is added
![image](https://user-images.githubusercontent.com/83949077/123772952-e40d7980-d8e9-11eb-8e82-c16e2a174882.png)

**Comment by yash-bitpod** [comment]
The respective ui is generated and handled by paypal, please log an issue on their end accordingly if required.
