### ISSUE TITLE
Paypal>> when payment is in process Paypal button is showing

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#915]
**Describe the bug**
when we click on pay in paypal payment is  in process and paypal button is also showing 

**To Reproduce**
1. Go to event
2. Register paid tickets using paypal
3. while payment is in process paypal button is showing 

**Expected behavior**
When payment is in process paypal button should display

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/123792598-6bfd7e80-d8fe-11eb-978f-21a1a4735089.png)

**Comment by yash-bitpod** [comment]
Duplicate of https://github.com/bitpodio/bitpodjs/issues/916
