### ISSUE TITLE
Registration form - Privacy policy checkbox should be hidden if the privacy policy url is not setup at the org level

### ISSUE THREAD

**Issue by neeraj-gulati** [bitpodio/bitpodjs#926]
hide privacy policy checkbox if the privacy policy url is empty/null at the org level.

![image](https://user-images.githubusercontent.com/68544907/123998325-0210d200-d9ef-11eb-9b8d-b0624f9e2604.png)

**Comment by rishi9684** [comment]
check diff scenario for for privacy policy
