### ISSUE TITLE
Registration Detail page=>Payment details are not displayed for Paytm ,Partial details displayed for Paypa

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#927]
-Login to event app and set the payment gateway to Paytm ,then Braintree/Paypal
-Register for an event with paid tickets and make payments through each of the above 3 payment methods
1)No details are displayed on Registration details for payment done thru paytm except for transaction id for both card n paytm wallet pay
2)Partial details (Last 4 digits of the card not displayed) are displayed in case paypal card payment option is selected 
3)For Braintree cards & Stripe card details are displayed

**Comment by lokeshbitpod** [comment]
As discussed with @SukantGujar for paypal and paytm we will display transactionId and card type i.e payment mode paypal account or paytm account

**Comment by pallaviumap** [comment]
As per discussion with @lokeshbitpod following is the current expected behavior which is being reflected
1)For Paypal
  -For Paylpal balance=>Mode of payment(Paypal) in Card type,Name & transaction id is displayed but last 4 digits of the card are not
  -For Paypal credit card=>Same as above for paypal
2)For Paytm
 -For card payment->Mode of payment=>Paytm in card type and transaction id is displayed no name or last 4 digits of card are displayed
 -For wallet payment=>same as above for paytm
3)Stripe =>Card type(Visa/Mastercard etc).name,last 4 digits of card and transaction id is displayed
4)Braintree cards=>Same as stripe

**Comment by pallaviumap** [comment]
same as in above comment is reflected in prod
