### ISSUE TITLE
EventDetails>>when we open event detail page blank popup is showing for 3 dots action menu for ticket grid

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#928]
**Describe the bug**
in prod when we open event detail page blank popup is showing for 3 dots action menu for ticket grid

**To Reproduce**
1. Go to event detail view 
2. go to ticket grid
3. see 3 dot actions 

**Expected behavior**
blank pop up should not display on 3 dot actions

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/124080019-7c7d3880-da67-11eb-9879-62ca41c80ca8.png)

**Comment by Bhagyshree10** [comment]
verified

**Comment by pallaviumap** [comment]
Verified in prod on 20-Jul -21
