### ISSUE TITLE
Event Details=>Remaining ticket count not reflected on Registration site if "Show Remaining ticket count" is checked 

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#930]
-Login to event app
-Go to the event details page of an event with Tickets
-If we check the "show Remaining Ticket count" for that event, it should be reflected  on the registration site
-Currently it is not reflected/displayed on the registration site
-In case of No ticket event, this option should not be displayed & should be hidden
![image](https://user-images.githubusercontent.com/83949077/124086623-de8d6c00-da6e-11eb-8dd9-df05a71b27af.png)

**Comment by neeraj-gulati** [comment]
@lokeshbitpod @pallaviumap lets hide this option from admin UI for now. We dont need this feature at the moment.

**Comment by pallaviumap** [comment]
The option is now not visible for existing single or rec events or for newly created single n rec events
