### ISSUE TITLE
Checkin>> not able to add attendees from check in page 

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#934]
**Describe the bug**
when we add attendee from check in page its not getting added in grid 

**To Reproduce**
1. Go to event app
2. go to event 
3. go to check in 
4. add attendee
5. see the record

**Expected behavior**
record should display attendees when we add  attendee on check in screen

**Screenshots**
I
![image](https://user-images.githubusercontent.com/71262809/124281067-fb0ccf80-db66-11eb-802b-d689bb6ad1a7.png)

**Comment by rishi9684** [comment]
As discuss with bhagyashree action removed so issue will not occur (709)
