### ISSUE TITLE
No ticket >>checkbox is not required For no ticket event 

### ISSUE THREAD

**Issue by Bhagyshree10** [bitpodio/bitpodjs#949]
**Describe the bug**
checkbox is not required For no ticket event 

**To Reproduce**
check for no ticket 

**Screenshots**
![image](https://user-images.githubusercontent.com/71262809/124758088-de4c0f80-df4b-11eb-8edb-56ead6d88618.png)

**Comment by pallaviumap** [comment]
Plz remove the check box for discount grid as well for no ticket event
