### ISSUE TITLE
Email=>Verification code for bitpod account creation lands in promotions and not primary inbox

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#996]
#1 -When the user tries to create bitpod account directly from login page or from user profile , the verification code sent lands in "Promotions" and not Primary inbox
#2 -when personal gmail account is used, then registration n reminder emails land in promotions and not primary inbox

**Comment by Amartyakumar** [comment]
https://sendgrid.com/blog/i-fought-the-tabs-and-the-tabs-won/
This is not possible to fix as gmail have their own mechanism to sort the mails and send them to promotion to inbox mails

**Comment by pallaviumap** [comment]
> https://sendgrid.com/blog/i-fought-the-tabs-and-the-tabs-won/
> This is not possible to fix as gmail have their own mechanism to sort the mails and send them to promotion to inbox mails
ok then ,closing the issue
