### ISSUE TITLE
Email=>If the email contains words "Test" "Trial" then email for verification is not send

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#997]
-If the email id contains words like "Test" "Trial" then the email for verification code for bitpod account set up is not send and so bitpod account for that email id can never be set up
It could be the configuration n security of send grid .

**Comment by Amartyakumar** [comment]
All the emails which are being bounced by the sendgrid are not getting emails as bounced mail do not receive mails.This will be a  task which to be discussed with Sukant later on

**Comment by pallaviumap** [comment]
#1077 =>Closing #997 ,any reference to it should be taken from #1077
